#16 one to many and many to one
bobocode-breskul/bibernate pull request #28
Opened 2024-01-30 20:22 UTC by AlexandrKarpachov

2024-02-01 15:53 UTC, JoshukLite requested changes

2024-02-01 15:53 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/annotation/JoinColumn.java
> +  boolean updatable() default true;
It's good to have either TODO for documentation or documentation itself

2024-02-01 15:53 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/persistence/GenericDao.java
> +    System.out.println("Bibirnate: " + sql);  // todo make this print depend on property.
How about to use logger here?

2024-02-01 15:53 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/util/EntityUtil.java
> +  public static boolean isPrimitiveColumn(Field field) {
`isPrimitiveColumn` name is ambiguous, it might refer to primitive values only. How about `isSimpleColumn` or something in that direction?

2024-02-01 15:53 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/persistence/Test.java
> +public class Test {
This should be either removed or put into `demo` package

2024-02-01 19:12 UTC, RomanPryshchepa commented on src/main/java/com/breskul/bibernate/persistence/GenericDao.java
> +  public static final String SELECT_BY_FIELD_VALUE_QUERY = "SELECT %s FROM %s WHERE %s = ?";
should be private I think

2024-02-01 19:14 UTC, RomanPryshchepa commented on src/main/java/com/breskul/bibernate/persistence/GenericDao.java
> +    System.out.println("Bibirnate: " + sql);  // todo make this print depend on property.
BibErnate :)

2024-02-01 19:20 UTC, RomanPryshchepa approved these changes

2024-02-03 10:04 UTC, JoshukLite approved these changes

2024-02-03 17:29 UTC, merged