15 implement transaction logic on program level
bobocode-breskul/bibernate pull request #35
Opened 2024-01-31 23:19 UTC by s-barabash

2024-02-01 12:57 UTC, OlehYakovenko approved these changes

2024-02-01 16:05 UTC, JoshukLite requested changes

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/action/Action.java
> +  int priority();
Either add todo for documentation or the documentation itself.

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/exception/DuplicateEntityException.java
> +public class DuplicateEntityException extends RuntimeException {
Same as above

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/transaction/Transaction.java
> +public class Transaction {
Docs

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/transaction/Transaction.java
> +      connection.setAutoCommit(true);
Is it explicitly set without using the method below `setAutoCommitTrue`?

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/transaction/Transaction.java
> +      throw new IllegalStateException("Cannot begin Transaction on closed session");
Is this message correct? Begin transaction during rollback?

2024-02-01 16:05 UTC, JoshukLite commented on src/main/java/com/breskul/bibernate/transaction/TransactionStatus.java
> +public enum TransactionStatus {
Class docs

2024-02-01 19:28 UTC, RomanPryshchepa approved these changes

2024-02-04 14:07 UTC, JoshukLite approved these changes

2024-02-05 21:11 UTC, merged