#75 fixed BiQLMapper
bobocode-breskul/bibernate pull request #76
Opened 2024-02-14 18:44 UTC by RomanPryshchepa

#75 fixed BiQLMapper

2024-02-14 19:05 UTC, mykolaFilimonov approved these changes

2024-02-14 19:50 UTC, s-barabash requested changes
Could you please add test for corner case

2024-02-14 21:37 UTC, JoshukLite approved these changes

2024-02-15 07:16 UTC, OlehYakovenko approved these changes

2024-02-15 18:22 UTC, RomanPryshchepa commented
> Could you please add test for corner case

Done

2024-02-15 18:23 UTC, s-barabash approved these changes

2024-02-15 18:24 UTC, s-barabash requested changes
Build is failing

2024-02-15 18:27 UTC, s-barabash approved these changes

2024-02-15 18:28 UTC, merged